# Load processsed data
df, temps_comp what more? why df_comp?

In [1]:
import pandas as pd

In [2]:
from my_functions import overarching_risks,environmental_and_occupational_risks,behavioural_risks,metabolic_risks,wata,pollu,temp,otherenvir,occupation,childfood,tobacco, childabuse, dietary_risks

In [3]:
temps_comp=pd.read_csv('./data/processed_data/temps_comp.csv')
df=pd.read_csv('./data/processed_data/df.csv')
df_comp=pd.read_csv('./data/processed_data/df_comp.csv')
summary_wide=pd.read_csv('./tables/Supplementary Data File 1.csv')
summary_wide_cons=pd.read_csv('./tables/Supplementary Data File 2.csv')

In [4]:
pd.set_option('display.float_format', '{:.6f}'.format)

In [5]:
df[(df['Risk_factor'].isin(tobacco))].groupby(['measure']).mean('val')

,Level,year_gbd,anal_year,val,lower,upper
measure,,,,,,
DALYs,3.000000,2018.600000,2009.564706,72110133.986135,61647459.246780,82833961.532185
Deaths,3.000000,2018.600000,2009.564706,2666053.314230,2316681.249529,3020084.653438

In [6]:
df[(df['Risk_factor'].isin(childabuse))].groupby(['measure']).mean('val')

,Level,year_gbd,anal_year,val,lower,upper
measure,,,,,,
DALYs,2.750000,2018.851852,2009.987654,5975589.942987,3337259.920561,9841928.289186
Deaths,2.666667,2018.482759,2009.793103,43248.907806,24102.389352,67937.510515

## intext numbers LEVEL 1 RISKS

In [7]:
temps_comp[(temps_comp['Risk_factor'] == 'Metabolic risks') & (temps_comp['year_gbd'].isin([2013, 2021]))&(temps_comp['measure']=='Deaths')]

,Level,Risk_factor,measure,year_gbd,anal_year,val,lower,upper,Group,Overarching_group
136,NaN,Metabolic risks,Deaths,2013,2013,15723000.000000,14719000.000000,16767000.000000,Other,Metabolic risks
722,NaN,Metabolic risks,Deaths,2021,2021,18562545.855514,16337592.799454,20590813.154793,Other,Metabolic risks

In [8]:
temps_comp[(temps_comp['Risk_factor'] == 'Behavioural risks') & (temps_comp['year_gbd'].isin([2017, 2021]))&(temps_comp['measure']=='Deaths')]

,Level,Risk_factor,measure,year_gbd,anal_year,val,lower,upper,Group,Overarching_group
447,1.000000,Behavioural risks,Deaths,2017,2017,23800000.000000,23100000.000000,24600000.000000,Other,Behavioural risks
732,NaN,Behavioural risks,Deaths,2021,2021,19115962.710292,14801075.558921,22678617.425391,Other,Behavioural risks

In [9]:
temps_comp[(temps_comp['Risk_factor'] == 'All risk factors') & (temps_comp['year_gbd'].isin([2013, 2021]))&(temps_comp['measure']=='DALYs')]

,Level,Risk_factor,measure,year_gbd,anal_year,val,lower,upper,Group,Overarching_group
143,NaN,All risk factors,DALYs,2013,2013,996554000.000000,927157000.000000,1072340000.000000,Other,All risk factors
782,NaN,All risk factors,DALYs,2021,2021,1194160305.997880,1098926339.228440,1310811109.345070,Other,All risk factors

In [10]:
temps_comp[(temps_comp['Risk_factor'].isin(['Metabolic risks', 'Environmental/occupational risks'])) & (temps_comp['year_gbd'].isin([2013, 2021]))&(temps_comp['measure']=='DALYs')]

,Level,Risk_factor,measure,year_gbd,anal_year,val,lower,upper,Group,Overarching_group
144,NaN,Environmental/occupational risks,DALYs,2013,2013,289517000.000000,265778000.000000,312094000.000000,Other,Environmental/occupational risks
193,NaN,Metabolic risks,DALYs,2013,2013,373817000.000000,343978000.000000,403889000.000000,Other,Metabolic risks
783,NaN,Environmental/occupational risks,DALYs,2021,2021,416369698.591555,363819533.065228,468501713.147278,Other,Environmental/occupational risks
792,NaN,Metabolic risks,DALYs,2021,2021,476078739.990901,412470868.224027,541393380.178398,Other,Metabolic risks

In [11]:
temps_comp[(temps_comp['Risk_factor']=='Behavioural risks') & (temps_comp['year_gbd'].isin([2016,2017,2013, 2021]))&(temps_comp['measure']=='DALYs')]

,Level,Risk_factor,measure,year_gbd,anal_year,val,lower,upper,Group,Overarching_group
163,NaN,Behavioural risks,DALYs,2013,2013,717608000.000000,667831000.000000,771924000.000000,Other,Behavioural risks
389,1.000000,Behavioural risks,DALYs,2016,2016,781103690.000000,737052730.000000,830058540.000000,Other,Behavioural risks
508,1.000000,Behavioural risks,DALYs,2017,2017,913000000.000000,863000000.000000,961000000.000000,Other,Behavioural risks
778,NaN,Behavioural risks,DALYs,2021,2021,763258561.843508,649014978.895996,865224121.841111,Other,Behavioural risks

## intext numbers LEVEL 2 RISKS

In [12]:
df_comp[(df_comp['Risk_factor'] == 'Air pollution') & 
    (df_comp['measure'] == 'Deaths') & 
    (df_comp['year_gbd'].isin([2017, 2021]))]

,Level,Risk_factor,measure,year_gbd,anal_year,val,lower,upper
608,2.000000,Air pollution,Deaths,2017,2017,4900000.000000,4420000.000000,5390000.000000
995,NaN,Air pollution,Deaths,2021,2021,8079995.357754,6709212.885182,9483055.070014

In [13]:
df_comp[(df_comp['Risk_factor'] == 'Dietary risks') & 
    (df_comp['measure'] == 'Deaths') & 
    (df_comp['year_gbd'].isin([2013, 2019]))]

,Level,Risk_factor,measure,year_gbd,anal_year,val,lower,upper
176,NaN,Dietary risks,Deaths,2013,2013,11274000.000000,9656000.000000,12957000.000000
791,NaN,Dietary risks,Deaths,2019,2019,7943046.066217,6472323.455616,9757376.792491

In [14]:
df_comp[(df_comp['Risk_factor'] == 'Low physical activity') & 
    (df_comp['measure'] == 'Deaths') & 
    (df_comp['year_gbd'].isin([2013, 2021]))]

,Level,Risk_factor,measure,year_gbd,anal_year,val,lower,upper
195,NaN,Low physical activity,Deaths,2013,2013,2182000.000000,1858000.000000,2555000.000000
1006,NaN,Low physical activity,Deaths,2021,2021,657618.695735,278741.786774,1058456.233423

In [15]:
df_comp[(df_comp['Risk_factor'] == 'Air pollution') & 
    (df_comp['measure'] == 'DALYs') & 
    (df_comp['year_gbd'].isin([2017, 2019]))]

,Level,Risk_factor,measure,year_gbd,anal_year,val,lower,upper
688,2.000000,Air pollution,DALYs,2017,2017,147000000.000000,132000000.000000,162000000.000000
852,NaN,Air pollution,DALYs,2019,2019,213284886.633513,188894775.428659,239530188.999461

In [16]:
213284886.633513-147000000.000000

66284886.633513

In [17]:
df_comp[(df_comp['Risk_factor'] == 'Dietary risks') & 
    (df_comp['measure'] == 'DALYs') & 
    (df_comp['year_gbd'].isin([2017, 2019]))]

,Level,Risk_factor,measure,year_gbd,anal_year,val,lower,upper
737,2.000000,Dietary risks,DALYs,2017,2017,255000000.000000,234000000.000000,274000000.000000
875,NaN,Dietary risks,DALYs,2019,2019,187695611.722531,155915464.870632,225396721.892824

In [18]:
255000000-187695611.722531

67304388.27746901

In [19]:
df_comp[(df_comp['Risk_factor'] == 'Child and maternal malnutrition') & 
    (df_comp['measure'] == 'DALYs') & 
    (df_comp['year_gbd'].isin([2015, 2016]))]

,Level,Risk_factor,measure,year_gbd,anal_year,val,lower,upper
394,NaN,Child and maternal malnutrition,DALYs,2015,2015,172120000.000000,151792000.000000,196176000.000000
554,2.000000,Child and maternal malnutrition,DALYs,2016,2016,275068980.000000,255117960.000000,296600820.000000

In [20]:
(275068980.000000-172120000.000000)/1000000

102.94898

## intext numbers LEVEL 3 RISKS

In [21]:
temps_comp[(temps_comp['Risk_factor']=='Smoking') & (temps_comp['anal_year'].isin([2019,2021]))]

,Level,Risk_factor,measure,year_gbd,anal_year,val,lower,upper,Group,Overarching_group
564,NaN,Smoking,Deaths,2019,2019,7693367.948221,7158449.614296,8200590.607250,Tobacco,Behavioural risks
626,NaN,Smoking,DALYs,2019,2019,199794745.476503,185451306.073709,213815712.326619,Tobacco,Behavioural risks
677,NaN,Smoking,Deaths,2021,2021,6175019.075387,5047660.837167,7226384.616746,Tobacco,Behavioural risks
739,NaN,Smoking,DALYs,2021,2021,165080664.209595,135430162.197463,193938447.453166,Tobacco,Behavioural risks

In [22]:
(7693367.948221-6175019.075387)/1000000

1.5183488728339998

In [23]:
(199794745.476503-165080664.209595)/1000000

34.71408126690802

In [24]:
temps_comp[(temps_comp['Risk_factor']=='Particulate matter pollution') & (temps_comp['anal_year'].isin([2019,2017]))]

,Level,Risk_factor,measure,year_gbd,anal_year,val,lower,upper,Group,Overarching_group
435,3.000000,Particulate matter pollution,Deaths,2017,2017,4580000.000000,4130000.000000,5030000.000000,Air pollution,Environmental/occupational risks
494,3.000000,Particulate matter pollution,DALYs,2017,2017,143000000.000000,129000000.000000,156000000.000000,Air pollution,Environmental/occupational risks
609,NaN,Particulate matter pollution,Deaths,2019,2019,6454962.236974,5718170.178532,7235588.482372,Air pollution,Environmental/occupational risks
673,NaN,Particulate matter pollution,DALYs,2019,2019,209689842.874868,185903374.812178,235165660.692867,Air pollution,Environmental/occupational risks

In [25]:
temps_comp[(temps_comp['Risk_factor']=='Particulate matter pollution')]

,Level,Risk_factor,measure,year_gbd,anal_year,val,lower,upper,Group,Overarching_group
435,3.000000,Particulate matter pollution,Deaths,2017,2017,4580000.000000,4130000.000000,5030000.000000,Air pollution,Environmental/occupational risks
494,3.000000,Particulate matter pollution,DALYs,2017,2017,143000000.000000,129000000.000000,156000000.000000,Air pollution,Environmental/occupational risks
609,NaN,Particulate matter pollution,Deaths,2019,2019,6454962.236974,5718170.178532,7235588.482372,Air pollution,Environmental/occupational risks
673,NaN,Particulate matter pollution,DALYs,2019,2019,209689842.874868,185903374.812178,235165660.692867,Air pollution,Environmental/occupational risks
701,NaN,Particulate matter pollution,Deaths,2021,2021,7833220.915388,6479473.762984,9263395.346069,Air pollution,Environmental/occupational risks
766,NaN,Particulate matter pollution,DALYs,2021,2021,231511232.938127,194538892.195336,270855451.370096,Air pollution,Environmental/occupational risks

In [26]:
7.8-4.6

3.2

In [27]:
(231511232.938127-143000000.000000)/1000000

88.51123293812701

In [28]:
temps_comp[(temps_comp['Risk_factor']=='Occupational injuries')]

,Level,Risk_factor,measure,year_gbd,anal_year,val,lower,upper,Group,Overarching_group
42,NaN,Occupational injuries,Deaths,2010,2010,481429.000000,363778.000000,639590.000000,Occupational risks,Environmental/occupational risks
86,NaN,Occupational injuries,DALYs,2010,2010,23444000.000000,17736000.000000,30904000.000000,Occupational risks,Environmental/occupational risks
105,NaN,Occupational injuries,Deaths,2013,2013,159000.000000,127000.000000,206000.000000,Occupational risks,Environmental/occupational risks
161,NaN,Occupational injuries,DALYs,2013,2013,9947000.000000,7886000.000000,12927000.000000,Occupational risks,Environmental/occupational risks
217,NaN,Occupational injuries,Deaths,2015,2015,204000.000000,191000.000000,232000.000000,Occupational risks,Environmental/occupational risks
273,NaN,Occupational injuries,DALYs,2015,2015,13492000.000000,12006000.000000,15545000.000000,Occupational risks,Environmental/occupational risks
329,3.000000,Occupational injuries,Deaths,2016,2016,335710.000000,328640.000000,343270.000000,Occupational risks,Environmental/occupational risks
387,3.000000,Occupational injuries,DALYs,2016,2016,21774600.000000,19810660.000000,24090160.000000,Occupational risks,Environmental/occupational risks
446,3.000000,Occupational injuries,Deaths,2017,2017,304000.000000,288000.000000,323000.000000,Occupational risks,Environmental/occupational risks
506,3.000000,Occupational injuries,DALYs,2017,2017,21100000.000000,19200000.000000,23500000.000000,Occupational risks,Environmental/occupational risks
592,NaN,Occupational injuries,Deaths,2019,2019,311490.532760,283714.750716,343372.949868,Occupational risks,Environmental/occupational risks
655,NaN,Occupational injuries,DALYs,2019,2019,22419935.587021,19842434.548992,25396791.377680,Occupational risks,Environmental/occupational risks
714,NaN,Occupational injuries,Deaths,2021,2021,480609.339767,452246.387531,507681.149764,Occupational risks,Environmental/occupational risks
747,NaN,Occupational injuries,DALYs,2021,2021,31859651.364044,29105520.446085,34891501.724888,Occupational risks,Environmental/occupational risks

In [29]:
temps_comp[(temps_comp['Risk_factor']=='Smoking') & (temps_comp['anal_year'].isin([2010,2019,2021]))].sort_values(by='measure')

,Level,Risk_factor,measure,year_gbd,anal_year,val,lower,upper,Group,Overarching_group
57,NaN,Smoking,DALYs,2010,2010,136907000.000000,117201000.000000,153778000.000000,Tobacco,Behavioural risks
626,NaN,Smoking,DALYs,2019,2019,199794745.476503,185451306.073709,213815712.326619,Tobacco,Behavioural risks
739,NaN,Smoking,DALYs,2021,2021,165080664.209595,135430162.197463,193938447.453166,Tobacco,Behavioural risks
13,NaN,Smoking,Deaths,2010,2010,5695349.000000,4755779.000000,6421611.000000,Tobacco,Behavioural risks
564,NaN,Smoking,Deaths,2019,2019,7693367.948221,7158449.614296,8200590.607250,Tobacco,Behavioural risks
677,NaN,Smoking,Deaths,2021,2021,6175019.075387,5047660.837167,7226384.616746,Tobacco,Behavioural risks

In [30]:
summary_wide[summary_wide['rmu_Deaths']>1]

,Unnamed: 0,Overarching_group,Group,Risk_factor,median_Deaths,min_Deaths,max_Deaths,n_estimates_Deaths,mean_Deaths,std_Deaths,...,mad_DALYs,range_DALYs,fold_range_vs_median_DALYs,rmu_DALYs,cv_DALYs,max_vs_min_DALYs,f_med_DALYs,rcv_m_DALYs,Median Deaths (Min-Max),Median DALYs (Min-Max)
4,4,Behavioural risks,Child and maternal malnutrition,Iron deficiency,60000.000000,20950.000000,199000.000000,7.000000,80028.400000,62101.400000,...,4586744.900000,21606874.900000,0.600000,0.500000,0.200000,1.700000,1.500000,0.200000,60000.0 (20950.0-199000.0),35849870.0 (31263125.1-52870000.0)
6,6,Behavioural risks,Child and maternal malnutrition,Suboptimal breastfeeding,169000.000000,101023.100000,544817.000000,7.000000,286520.300000,186849.900000,...,5860250.600000,38397250.600000,2.600000,1.500000,0.600000,5.200000,3.200000,0.600000,169000.0 (101023.1-544817.0),15000000.0 (9139749.4-47537000.0)
7,7,Behavioural risks,Child and maternal malnutrition,Vitamin A deficiency,83000.000000,17374.400000,233000.000000,7.000000,86309.500000,74442.900000,...,3631950.000000,26336244.300000,3.500000,2.800000,1.000000,10.900000,3.800000,0.700000,83000.0 (17374.4-233000.0),7611000.0 (2663755.7-29000000.0)
8,8,Behavioural risks,Child and maternal malnutrition,Zinc deficiency,29000.000000,1611.600000,97330.000000,7.000000,39548.200000,35087.200000,...,2387000.000000,8987553.000000,3.500000,2.500000,0.900000,61.500000,17.400000,1.400000,29000.0 (1611.6-97330.0),2580000.0 (148447.0-9136000.0)
9,9,Behavioural risks,Dietary risks,Diet high in \nsugar sweetened beverages,126000.000000,22560.000000,299521.000000,7.000000,134574.900000,103294.800000,...,1857561.800000,7773490.000000,1.700000,1.700000,0.600000,11.000000,5.700000,0.600000,126000.0 (22560.0-299521.0),4450000.0 (779510.0-8553000.0)
10,10,Behavioural risks,Dietary risks,Diet high in processed meat,304284.400000,130000.000000,840857.000000,7.000000,413575.700000,268734.600000,...,6787091.000000,17742960.000000,1.700000,1.600000,0.600000,6.600000,3.200000,1.000000,304284.4 (130000.0-840857.0),10357091.0 (3196040.0-20939000.0)
11,11,Behavioural risks,Dietary risks,Diet high in red meat,43000.000000,25000.000000,895674.900000,7.000000,209931.300000,321597.900000,...,605670.000000,22613743.800000,12.200000,3.600000,1.300000,19.100000,12.900000,0.500000,43000.0 (25000.0-895674.9),1853000.0 (1247330.0-23861073.8)
13,13,Behavioural risks,Dietary risks,Diet high in trans fatty acids,405000.000000,93310.700000,644981.000000,7.000000,369741.700000,189096.900000,...,3715000.000000,11742241.600000,1.200000,1.300000,0.500000,5.700000,4.000000,0.600000,405000.0 (93310.7-644981.0),9875000.0 (2491995.3-14234237.0)
17,17,Behavioural risks,Dietary risks,Diet low in fruits,2420000.000000,1046014.900000,4902242.000000,7.000000,2678578.400000,1249475.900000,...,9997000.000000,76416663.800000,1.200000,1.200000,0.400000,3.800000,2.300000,0.200000,2420000.0 (1046014.9-4902242.0),64800000.0 (27678336.2-104095000.0)
18,18,Behavioural risks,Dietary risks,Diet low in legumes,603735.000000,389328.800000,1116424.000000,4.000000,678305.700000,314126.300000,...,2525941.600000,15146471.800000,1.200000,1.000000,0.500000,2.700000,1.900000,0.300000,603735.0 (389328.8-1116424.0),12607225.0 (9162566.8-24309038.5)
20,20,Behavioural risks,Dietary risks,Diet low in nuts and seeds,2060000.000000,575139.200000,2471823.000000,7.000000,1606607.000000,781309.100000,...,1878000.000000,37693903.500000,0.800000,1.000000,0.500000,3.800000,3.600000,0.100000,2060000.0 (575139.2-2471823.0),49411000.0 (13595096.5-51289000.0)
21,21,Behavioural risks,Dietary risks,Diet low in seafood omega-3 fatty acids,1389896.000000,337279.700000,1538760.000000,7.000000,1119468.300000,472191.600000,...,5148840.000000,25938185.100000,0.900000,1.100000,0.400000,4.500000,3.800000,0.300000,1389896.0 (337279.7-1538760.0),28199000.0 (7409654.9-33347840.0)
27,27,Behavioural risks,Intimate partner violence,Intimate partner violence,86503.300000,61276.900000,197000.000000,7.000000,121890.700000,64097.400000,...,2922674.200000,11218710.000000,1.300000,1.100000,0.400000,3.000000,2.000000,0.500000,86503.3 (61276.9-197000.0),8497964.2 (5575290.0-16794000.0)
28,28,Behavioural risks,Low physical activity,Low physical activity,1373340.000000,657618.700000,3183940.000000,7.000000,1584771.500000,865220.400000,...,8610899.600000,53613039.600000,2.200000,1.600000,0.600000,4.400000,2.900000,0.500000,1373340.0 (657618.7-3183940.0),24315860.0 (15704960.4-69318000.0)
36,36,Environmental/occupational risks,Air pollution,Ambient ozone pollution,254000.000000,152434.000000,489518.800000,7.000000,311973.600000,131615.700000,...,1276170.000000,6317024.500000,1.200000,1.200000,0.400000,3.600000,2.100000,0.400000,254000.0 (152434.0-489518.8),5073000.0 (2456000.0-8773024.5)
44,44,Environmental/occupational risks,Occupational risks,Occupational carcinogens,341997.800000,118097.000000,746540.000000,7.000000,383422.900000,193632.200000,...,1654983.100000,18001730.000000,2.400000,2.100000,0.700000,7.700000,2.800000,0.300000,341997.8 (118097.0-746540.0),7457983.1 (2681000.0-20682730.0)
50,50,Environmental/occupational risks,Other environmental risks,Lead exposure,853000.000000,495000.000000,1541908.700000,7.000000,865100.400000,358907.600000,...,4833385.300000,24603550.800000,1.500000,1.300000,0.400000,3.600000,2.000000,0.400000,853000.0 (495000.0-1541908.7),16843000.0 (9287000.0-33890550.8)
51,51,Environmental/occupational risks,Other environmental risks,Other environmental risks,945000.000000,558000.000000,1624069.100000,7.000000,946179.700000,365311.700000,...,4739861.600000,25115601.800000,1.300000,1.200000,0.400000,3.400000,1.900000,0.400000,945000.0 (558000.0-1624069.1),18822000.0 (10673000.0-35788601.8)
55,55,Environmental/occupational risks,"Unsafe water, sanitation, and handwashing",Unsafe water source,1230000.000000,116126.000000,1251000.000000,7.000000,1005132.300000,423300.400000,...,11225000.000000,67350000.000000,1.100000,1.200000,0.400000,9.700000,8.200000,0.300000,1230000.0 (116126.0-1251000.0),63900000.0 (7775000.0-75125000.0)

## R/M analysis

### Across iteration year comparisons

In [31]:
summary_wide.rmu_Deaths.median()

0.7

In [32]:
print('Median range/median deaths risks 2010-2021: '+str(summary_wide.rmu_Deaths.median())+' ('+str(summary_wide.rmu_Deaths.min())+'-'+str(summary_wide.rmu_Deaths.max())+')',
    '\nMedian range/median daly risks 2010-2021: '+str(summary_wide.rmu_DALYs.median())+' ('+str(summary_wide.rmu_DALYs.min())+'-'+str(summary_wide.rmu_DALYs.max())+')')

Median range/median deaths risks 2010-2021: 0.7 (0.0-4.1)
Median range/median daly risks 2010-2021: 0.6 (0.0-3.6)

In [33]:
summary_wide.head(3)

,Unnamed: 0,Overarching_group,Group,Risk_factor,median_Deaths,min_Deaths,max_Deaths,n_estimates_Deaths,mean_Deaths,std_Deaths,...,mad_DALYs,range_DALYs,fold_range_vs_median_DALYs,rmu_DALYs,cv_DALYs,max_vs_min_DALYs,f_med_DALYs,rcv_m_DALYs,Median Deaths (Min-Max),Median DALYs (Min-Max)
0,0,All risk factors,Other,All risk factors,33421437.000000,30839000.000000,35000050.000000,6.000000,33169320.700000,1518884.600000,...,74492832.500000,216707691.000000,0.200000,0.200000,0.100000,1.200000,1.100000,0.100000,33421437.0 (30839000.0-35000050.0),1137138013.0 (996554000.0-1213261691.0)
1,1,Behavioural risks,Child and maternal malnutrition,Child and maternal malnutrition,2654950.700000,1414000.000000,3190000.000000,6.000000,2419450.900000,716510.200000,...,37336796.700000,154880000.000000,0.600000,0.600000,0.300000,1.900000,1.600000,0.200000,2654950.7 (1414000.0-3190000.0),273552858.0 (172120000.0-327000000.0)
2,2,Behavioural risks,Child and maternal malnutrition,Child growth failure,1037643.000000,888199.300000,1190000.000000,4.000000,1038371.300000,125178.200000,...,5120037.000000,25938542.900000,0.300000,0.300000,0.100000,1.400000,1.200000,0.100000,1037643.0 (888199.3-1190000.0),90479848.0 (74061457.1-100000000.0)

In [34]:
# Calculate medians for each group, skipping NaN values
behavioural_risks_median = summary_wide[summary_wide['Overarching_group'] == 'Behavioural risks'].rmu_Deaths.median(skipna=True)
environmental_risks_median = summary_wide[summary_wide['Overarching_group'] == 'Environmental/occupational risks'].rmu_Deaths.median(skipna=True)
metabolic_risks_median = summary_wide[summary_wide['Overarching_group'] == 'Metabolic risks'].rmu_Deaths.median(skipna=True)

# Print the results
print(f"Behavioural risks median R/M: {behavioural_risks_median}")
print(f"Environmental/occupational risks median R/M: {environmental_risks_median}")
print(f"Metabolic risks median R/M: {metabolic_risks_median}")

# Calculate medians for each group, skipping NaN values
behavioural_risks_median = summary_wide[summary_wide['Overarching_group'] == 'Behavioural risks'].rmu_DALYs.median(skipna=True)
environmental_risks_median = summary_wide[summary_wide['Overarching_group'] == 'Environmental/occupational risks'].fold_range_vs_median_DALYs.median(skipna=True)
metabolic_risks_median = summary_wide[summary_wide['Overarching_group'] == 'Metabolic risks'].rmu_DALYs.median(skipna=True)

# Print the results
print(f"Behavioural risks median R/M: {behavioural_risks_median}")
print(f"Environmental/occupational risks median R/M: {environmental_risks_median}")
print(f"Metabolic risks median R/M: {metabolic_risks_median}")

Behavioural risks median R/M: 0.95
Environmental/occupational risks median R/M: 0.7
Metabolic risks median R/M: 0.5
Behavioural risks median R/M: 0.75
Environmental/occupational risks median R/M: 0.5
Metabolic risks median R/M: 0.5

In [35]:
# Sort by 'Overarching_group' first
sorted_summary = summary_wide.sort_values(by='Overarching_group')

# Group by 'Group' and calculate the median for the specified columns
group_medians = sorted_summary.groupby('Group')[['rmu_Deaths', 'rmu_DALYs']].median()

# Display the result
group_medians

                                           rmu_Deaths  rmu_DALYs
Group
Air pollution                                0.500000   0.500000
Child and maternal malnutrition              1.100000   0.550000
Dietary risks                                1.050000   1.000000
Drug use                                     1.000000   0.600000
High LDL cholesterol*                        0.600000   0.700000
High alcohol use                             0.400000   0.600000
High body-mass index                         0.400000   0.500000
High fasting plasma glucose                  0.600000   0.600000
High systolic blood pressure                 0.100000   0.300000
Intimate partner violence                    1.100000   1.100000
Kidney dysfunction*                          0.500000   0.500000
Low bone mineral density                     0.700000   1.000000
Low physical activity                        1.600000   1.600000
Non-optimal temperature                      0.100000   0.000000
Occupational risks                           1.000000   0.500000
Other                                        0.200000   0.200000
Other environmental risks                    1.100000   1.200000
Tobacco                                      0.350000   0.450000
Unsafe sex                                   0.500000   0.600000
Unsafe water, sanitation, and handwashing    0.800000   0.800000

### Matched comparisons

In [36]:
summary_wide_cons[summary_wide_cons['rmu_Deaths']>1.5].Risk_factor.unique()

array(['Iron deficiency', 'Vitamin A deficiency', 'Zinc deficiency',
       'Diet high in \nsugar sweetened beverages',
       'Diet high in red meat', 'Diet high in trans fatty acids',
       'Diet low in fruits', 'Diet low in nuts and seeds',
       'Low physical activity'], dtype=object)

In [37]:
# Calculate and print the proportion and count of rows where rmu_Deaths > 1
prop_deaths_gt1 = summary_wide_cons['rmu_Deaths'].gt(1).mean()
count_deaths_gt1 = summary_wide_cons['rmu_Deaths'].gt(1).sum()
print(f'prop >1 fold range Deaths, n: {prop_deaths_gt1}, {count_deaths_gt1}')

# Calculate and print the proportion and count of rows where rmu_DALYs > 1
prop_dalys_gt1 = summary_wide_cons['rmu_DALYs'].gt(1).mean()
count_dalys_gt1 = summary_wide_cons['rmu_DALYs'].gt(1).sum()
print(f'prop >1 fold range DALYs, n: {prop_dalys_gt1}, {count_dalys_gt1}')

prop >1 fold range Deaths, n: 0.1490066225165563, 90
prop >1 fold range DALYs, n: 0.1390728476821192, 84

In [38]:
print('Median range/median deaths risks 2010-2021: '+str(summary_wide_cons.rmu_Deaths.median())+' ('+str(summary_wide_cons.rmu_Deaths.min())+'-'+str(summary_wide_cons.rmu_Deaths.max())+')',
    '\nMedian range/median daly risks 2010-2021: '+str(summary_wide_cons.rmu_DALYs.median())+' ('+str(summary_wide_cons.rmu_DALYs.min())+'-'+str(summary_wide_cons.rmu_DALYs.max())+')')

Median range/median deaths risks 2010-2021: 0.36454829328193983 (0.0-2.5810824229773317)
Median range/median daly risks 2010-2021: 0.3291107969842606 (0.0-2.5256558237360025)

In [39]:
## IQR for deaths and DALYs
summary_wide_cons['rmu_Deaths'].quantile(0.25), summary_wide_cons['rmu_Deaths'].quantile(0.75)

(0.17751081424297907, 0.7711610755766243)

In [ ]:
summary_wide_cons['rmu_DALYs'].quantile(0.25), summary_wide_cons['rmu_DALYs'].quantile(0.75)

(0.14549279317698363, 0.7251634275470046)