# Load processsed data
df, temps_comp what more? why df_comp?

In [48]:
import pandas as pd

In [49]:
from my_functions import overarching_risks,environmental_and_occupational_risks,behavioural_risks,metabolic_risks,wata,pollu,temp,otherenvir,occupation,childfood,tobacco, childabuse, dietary_risks

In [50]:
temps_comp=pd.read_csv('./data/processed_data/temps_comp.csv')
df=pd.read_csv('./data/processed_data/df.csv')
df_comp=pd.read_csv('./data/processed_data/df_comp.csv')
summary_wide=pd.read_csv('./tables/Supplementary Data File 1.csv')
summary_wide_cons=pd.read_csv('./tables/Supplementary Data File 2.csv')

In [51]:
pd.set_option('display.float_format', '{:.6f}'.format)

## intext numbers LEVEL 1 RISKS

In [54]:
temps_comp[(temps_comp['Risk_factor'] == 'Metabolic risks') & (temps_comp['year_gbd'].isin([2013, 2023]))&(temps_comp['measure']=='Deaths')]

,Level,Risk_factor,measure,year_gbd,anal_year,val,lower,upper,Group,Overarching_group
136,NaN,Metabolic risks,Deaths,2013,2013,15723000.000000,14719000.000000,16767000.000000,Other,Metabolic risks
821,NaN,Metabolic risks,Deaths,2023,2023,19020776.689004,17278812.217117,20554778.885926,Other,Metabolic risks

In [55]:
temps_comp[(temps_comp['Risk_factor'] == 'Behavioural risks') & (temps_comp['year_gbd'].isin([2017, 2021]))&(temps_comp['measure']=='Deaths')]

,Level,Risk_factor,measure,year_gbd,anal_year,val,lower,upper,Group,Overarching_group
447,1.000000,Behavioural risks,Deaths,2017,2017,23800000.000000,23100000.000000,24600000.000000,Other,Behavioural risks
732,NaN,Behavioural risks,Deaths,2021,2021,19115962.710292,14801075.558921,22678617.425391,Other,Behavioural risks

In [56]:
temps_comp[(temps_comp['Risk_factor'] == 'All risk factors') & (temps_comp['year_gbd'].isin([2013, 2023]))&(temps_comp['measure']=='Deaths')]

,Level,Risk_factor,measure,year_gbd,anal_year,val,lower,upper,Group,Overarching_group
88,NaN,All risk factors,Deaths,2013,2013,30839000.000000,29719000.000000,31949000.000000,Other,All risk factors
845,NaN,All risk factors,Deaths,2023,2023,34768400.049514,33129071.081033,36119705.812642,Other,All risk factors

In [57]:
temps_comp[(temps_comp['Risk_factor'].isin(['Metabolic risks', 'Environmental/occupational risks'])) & (temps_comp['year_gbd'].isin([2013, 2023]))&(temps_comp['measure']=='Deaths')]

,Level,Risk_factor,measure,year_gbd,anal_year,val,lower,upper,Group,Overarching_group
89,NaN,Environmental/occupational risks,Deaths,2013,2013,8181000.000000,7651000.000000,8726000.000000,Other,Environmental/occupational risks
136,NaN,Metabolic risks,Deaths,2013,2013,15723000.000000,14719000.000000,16767000.000000,Other,Metabolic risks
821,NaN,Metabolic risks,Deaths,2023,2023,19020776.689004,17278812.217117,20554778.885926,Other,Metabolic risks
847,NaN,Environmental/occupational risks,Deaths,2023,2023,13888792.582106,12441735.998986,15368436.584456,Other,Environmental/occupational risks

In [58]:
temps_comp[(temps_comp['Risk_factor']=='Behavioural risks') & (temps_comp['year_gbd'].isin([2016,2017,2013, 2021]))&(temps_comp['measure']=='DALYs')]

,Level,Risk_factor,measure,year_gbd,anal_year,val,lower,upper,Group,Overarching_group
163,NaN,Behavioural risks,DALYs,2013,2013,717608000.000000,667831000.000000,771924000.000000,Other,Behavioural risks
389,1.000000,Behavioural risks,DALYs,2016,2016,781103690.000000,737052730.000000,830058540.000000,Other,Behavioural risks
508,1.000000,Behavioural risks,DALYs,2017,2017,913000000.000000,863000000.000000,961000000.000000,Other,Behavioural risks
779,NaN,Behavioural risks,DALYs,2021,2021,763258561.843508,649014978.895996,865224121.841111,Other,Behavioural risks

## intext numbers LEVEL 2 RISKS

In [59]:
df_comp[(df_comp['Risk_factor'] == 'Air pollution') & 
    (df_comp['measure'] == 'Deaths') & 
    (df_comp['year_gbd'].isin([2017, 2021]))]

,Level,Risk_factor,measure,year_gbd,anal_year,val,lower,upper
608,2.000000,Air pollution,Deaths,2017,2017,4900000.000000,4420000.000000,5390000.000000
995,NaN,Air pollution,Deaths,2021,2021,8079995.357754,6709212.885182,9483055.070014

In [60]:
df_comp[(df_comp['Risk_factor'] == 'Dietary risks') & 
    (df_comp['measure'] == 'Deaths') & 
    (df_comp['year_gbd'].isin([2013, 2019]))]

,Level,Risk_factor,measure,year_gbd,anal_year,val,lower,upper
176,NaN,Dietary risks,Deaths,2013,2013,11274000.000000,9656000.000000,12957000.000000
791,NaN,Dietary risks,Deaths,2019,2019,7943046.066217,6472323.455616,9757376.792491

In [61]:
df_comp[(df_comp['Risk_factor'] == 'Low physical activity') & 
    (df_comp['measure'] == 'Deaths') & 
    (df_comp['year_gbd'].isin([2013, 2023]))]

,Level,Risk_factor,measure,year_gbd,anal_year,val,lower,upper
195,NaN,Low physical activity,Deaths,2013,2013,2182000.000000,1858000.000000,2555000.000000
1148,NaN,Low physical activity,Deaths,2023,2023,670086.822617,276153.555934,1034962.831130

In [62]:
df_comp[(df_comp['Risk_factor'] == 'Air pollution') & 
    (df_comp['measure'] == 'DALYs') & 
    (df_comp['year_gbd'].isin([2017, 2019]))]

,Level,Risk_factor,measure,year_gbd,anal_year,val,lower,upper
688,2.000000,Air pollution,DALYs,2017,2017,147000000.000000,132000000.000000,162000000.000000
852,NaN,Air pollution,DALYs,2019,2019,213284886.633513,188894775.428659,239530188.999461

In [63]:
213284886.633513-147000000.000000

66284886.633513

In [64]:
df_comp[(df_comp['Risk_factor'] == 'Dietary risks') & 
    (df_comp['measure'] == 'DALYs') & 
    (df_comp['year_gbd'].isin([2017, 2019]))]

,Level,Risk_factor,measure,year_gbd,anal_year,val,lower,upper
737,2.000000,Dietary risks,DALYs,2017,2017,255000000.000000,234000000.000000,274000000.000000
875,NaN,Dietary risks,DALYs,2019,2019,187695611.722531,155915464.870632,225396721.892824

In [65]:
255000000-187695611.722531

67304388.27746901

In [66]:
df_comp[(df_comp['Risk_factor'] == 'Child and maternal malnutrition') & 
    (df_comp['measure'] == 'DALYs') & 
    (df_comp['year_gbd'].isin([2015, 2016]))]

,Level,Risk_factor,measure,year_gbd,anal_year,val,lower,upper
394,NaN,Child and maternal malnutrition,DALYs,2015,2015,172120000.000000,151792000.000000,196176000.000000
554,2.000000,Child and maternal malnutrition,DALYs,2016,2016,275068980.000000,255117960.000000,296600820.000000

In [67]:
(275068980.000000-172120000.000000)/1000000

102.94898

## intext numbers LEVEL 3 RISKS

In [68]:
temps_comp[(temps_comp['Risk_factor']=='Smoking') & (temps_comp['anal_year'].isin([2019,2021]))]

,Level,Risk_factor,measure,year_gbd,anal_year,val,lower,upper,Group,Overarching_group
564,NaN,Smoking,Deaths,2019,2019,7693367.948221,7158449.614296,8200590.607250,Tobacco,Behavioural risks
626,NaN,Smoking,DALYs,2019,2019,199794745.476503,185451306.073709,213815712.326619,Tobacco,Behavioural risks
677,NaN,Smoking,Deaths,2021,2021,6175019.075387,5047660.837167,7226384.616746,Tobacco,Behavioural risks
739,NaN,Smoking,DALYs,2021,2021,165080664.209595,135430162.197463,193938447.453166,Tobacco,Behavioural risks

In [69]:
(7693367.948221-6175019.075387)/1000000

1.5183488728339998

In [70]:
(199794745.476503-165080664.209595)/1000000

34.71408126690802

In [71]:
temps_comp[(temps_comp['Risk_factor']=='Particulate matter pollution') & (temps_comp['anal_year'].isin([2019,2017]))]

,Level,Risk_factor,measure,year_gbd,anal_year,val,lower,upper,Group,Overarching_group
435,3.000000,Particulate matter pollution,Deaths,2017,2017,4580000.000000,4130000.000000,5030000.000000,Air pollution,Environmental/occupational risks
494,3.000000,Particulate matter pollution,DALYs,2017,2017,143000000.000000,129000000.000000,156000000.000000,Air pollution,Environmental/occupational risks
609,NaN,Particulate matter pollution,Deaths,2019,2019,6454962.236974,5718170.178532,7235588.482372,Air pollution,Environmental/occupational risks
673,NaN,Particulate matter pollution,DALYs,2019,2019,209689842.874868,185903374.812178,235165660.692867,Air pollution,Environmental/occupational risks

In [72]:
temps_comp[(temps_comp['Risk_factor']=='Particulate matter pollution')]

,Level,Risk_factor,measure,year_gbd,anal_year,val,lower,upper,Group,Overarching_group
435,3.000000,Particulate matter pollution,Deaths,2017,2017,4580000.000000,4130000.000000,5030000.000000,Air pollution,Environmental/occupational risks
494,3.000000,Particulate matter pollution,DALYs,2017,2017,143000000.000000,129000000.000000,156000000.000000,Air pollution,Environmental/occupational risks
609,NaN,Particulate matter pollution,Deaths,2019,2019,6454962.236974,5718170.178532,7235588.482372,Air pollution,Environmental/occupational risks
673,NaN,Particulate matter pollution,DALYs,2019,2019,209689842.874868,185903374.812178,235165660.692867,Air pollution,Environmental/occupational risks
701,NaN,Particulate matter pollution,Deaths,2021,2021,7833220.915388,6479473.762984,9263395.346069,Air pollution,Environmental/occupational risks
766,NaN,Particulate matter pollution,DALYs,2021,2021,231511232.938127,194538892.195336,270855451.370096,Air pollution,Environmental/occupational risks
859,NaN,Particulate matter pollution,Deaths,2023,2023,7667912.957881,6241004.322396,9064880.935541,Air pollution,Environmental/occupational risks
920,NaN,Particulate matter pollution,DALYs,2023,2023,227944406.040219,189924789.664386,260701417.089274,Air pollution,Environmental/occupational risks

In [73]:
7.8-4.6

3.2

In [74]:
(231511232.938127-143000000.000000)/1000000

88.51123293812701

In [75]:
temps_comp[(temps_comp['Risk_factor']=='Occupational injuries')]

,Level,Risk_factor,measure,year_gbd,anal_year,val,lower,upper,Group,Overarching_group
42,NaN,Occupational injuries,Deaths,2010,2010,481429.000000,363778.000000,639590.000000,Occupational risks,Environmental/occupational risks
86,NaN,Occupational injuries,DALYs,2010,2010,23444000.000000,17736000.000000,30904000.000000,Occupational risks,Environmental/occupational risks
105,NaN,Occupational injuries,Deaths,2013,2013,159000.000000,127000.000000,206000.000000,Occupational risks,Environmental/occupational risks
161,NaN,Occupational injuries,DALYs,2013,2013,9947000.000000,7886000.000000,12927000.000000,Occupational risks,Environmental/occupational risks
217,NaN,Occupational injuries,Deaths,2015,2015,204000.000000,191000.000000,232000.000000,Occupational risks,Environmental/occupational risks
273,NaN,Occupational injuries,DALYs,2015,2015,13492000.000000,12006000.000000,15545000.000000,Occupational risks,Environmental/occupational risks
329,3.000000,Occupational injuries,Deaths,2016,2016,335710.000000,328640.000000,343270.000000,Occupational risks,Environmental/occupational risks
387,3.000000,Occupational injuries,DALYs,2016,2016,21774600.000000,19810660.000000,24090160.000000,Occupational risks,Environmental/occupational risks
446,3.000000,Occupational injuries,Deaths,2017,2017,304000.000000,288000.000000,323000.000000,Occupational risks,Environmental/occupational risks
506,3.000000,Occupational injuries,DALYs,2017,2017,21100000.000000,19200000.000000,23500000.000000,Occupational risks,Environmental/occupational risks
592,NaN,Occupational injuries,Deaths,2019,2019,311490.532760,283714.750716,343372.949868,Occupational risks,Environmental/occupational risks
655,NaN,Occupational injuries,DALYs,2019,2019,22419935.587021,19842434.548992,25396791.377680,Occupational risks,Environmental/occupational risks
714,NaN,Occupational injuries,Deaths,2021,2021,480609.339767,452246.387531,507681.149764,Occupational risks,Environmental/occupational risks
747,NaN,Occupational injuries,DALYs,2021,2021,31859651.364044,29105520.446085,34891501.724888,Occupational risks,Environmental/occupational risks
840,NaN,Occupational injuries,Deaths,2023,2023,550628.182233,454727.967405,634881.412282,Occupational risks,Environmental/occupational risks
906,NaN,Occupational injuries,DALYs,2023,2023,41891476.638280,35426377.324892,49021879.823127,Occupational risks,Environmental/occupational risks

In [85]:
temps_comp[(temps_comp['Risk_factor']=='Lead exposure')]

,Level,Risk_factor,measure,year_gbd,anal_year,val,lower,upper,Group,Overarching_group
7,NaN,Lead exposure,Deaths,2010,2010,674038.000000,575858.000000,779314.000000,Other environmental risks,Environmental/occupational risks
51,NaN,Lead exposure,DALYs,2010,2010,13936000.000000,11750000.000000,16327000.000000,Other environmental risks,Environmental/occupational risks
100,NaN,Lead exposure,Deaths,2013,2013,853000.000000,572000.000000,1181000.000000,Other environmental risks,Environmental/occupational risks
155,NaN,Lead exposure,DALYs,2013,2013,16843000.000000,11494000.000000,23505000.000000,Other environmental risks,Environmental/occupational risks
212,NaN,Lead exposure,Deaths,2015,2015,495000.000000,237000.000000,815000.000000,Other environmental risks,Environmental/occupational risks
267,NaN,Lead exposure,DALYs,2015,2015,9287000.000000,4200000.000000,15594000.000000,Other environmental risks,Environmental/occupational risks
324,3.000000,Lead exposure,Deaths,2016,2016,540040.000000,269070.000000,868970.000000,Other environmental risks,Environmental/occupational risks
381,3.000000,Lead exposure,DALYs,2016,2016,13873550.000000,7578920.000000,21565040.000000,Other environmental risks,Environmental/occupational risks
441,3.000000,Lead exposure,Deaths,2017,2017,1050000.000000,709000.000000,1430000.000000,Other environmental risks,Environmental/occupational risks
500,3.000000,Lead exposure,DALYs,2017,2017,24400000.000000,16700000.000000,32800000.000000,Other environmental risks,Environmental/occupational risks
557,NaN,Lead exposure,Deaths,2019,2019,901715.875244,550909.466996,1288853.729871,Other environmental risks,Environmental/occupational risks
619,NaN,Lead exposure,DALYs,2019,2019,21676385.332857,13812877.437595,30297656.735969,Other environmental risks,Environmental/occupational risks
676,NaN,Lead exposure,Deaths,2021,2021,1541908.671250,-184924.271777,3224760.413801,Other environmental risks,Environmental/occupational risks
791,NaN,Lead exposure,DALYs,2021,2021,33890550.816460,-1428397.705994,67829855.336970,Other environmental risks,Environmental/occupational risks
811,NaN,Lead exposure,Deaths,2023,2023,3477003.684141,2579310.034638,4360538.383634,Other environmental risks,Environmental/occupational risks
870,NaN,Lead exposure,DALYs,2023,2023,73336765.759630,55182800.950154,91372003.061742,Other environmental risks,Environmental/occupational risks

In [76]:
temps_comp[(temps_comp['Risk_factor']=='Smoking') & (temps_comp['anal_year'].isin([2010,2019,2021]))].sort_values(by='measure')

,Level,Risk_factor,measure,year_gbd,anal_year,val,lower,upper,Group,Overarching_group
57,NaN,Smoking,DALYs,2010,2010,136907000.000000,117201000.000000,153778000.000000,Tobacco,Behavioural risks
626,NaN,Smoking,DALYs,2019,2019,199794745.476503,185451306.073709,213815712.326619,Tobacco,Behavioural risks
739,NaN,Smoking,DALYs,2021,2021,165080664.209595,135430162.197463,193938447.453166,Tobacco,Behavioural risks
13,NaN,Smoking,Deaths,2010,2010,5695349.000000,4755779.000000,6421611.000000,Tobacco,Behavioural risks
564,NaN,Smoking,Deaths,2019,2019,7693367.948221,7158449.614296,8200590.607250,Tobacco,Behavioural risks
677,NaN,Smoking,Deaths,2021,2021,6175019.075387,5047660.837167,7226384.616746,Tobacco,Behavioural risks

In [77]:
summary_wide[summary_wide['rmu_Deaths']>1]

,Unnamed: 0,Overarching_group,Group,Risk_factor,median_Deaths,min_Deaths,max_Deaths,n_estimates_Deaths,mean_Deaths,std_Deaths,...,mad_DALYs,range_DALYs,fold_range_vs_median_DALYs,rmu_DALYs,cv_DALYs,max_vs_min_DALYs,f_med_DALYs,rcv_m_DALYs,Median Deaths (Min-Max),Median DALYs (Min-Max)
4,4,Behavioural risks,Child and maternal malnutrition,Iron deficiency,51174.600000,20950.000000,199000.000000,8.000000,75196.300000,59096.900000,...,5475500.000000,21606874.900000,0.600000,0.500000,0.200000,1.700000,1.400000,0.200000,51174.6 (20950.0-199000.0),38919563.5 (31263125.1-52870000.0)
6,6,Behavioural risks,Child and maternal malnutrition,Suboptimal breastfeeding,160740.000000,101023.100000,544817.000000,8.000000,263885.400000,184456.100000,...,4841949.600000,38397250.600000,2.700000,1.700000,0.700000,5.200000,3.400000,0.500000,160740.0 (101023.1-544817.0),14186625.0 (9139749.4-47537000.0)
7,7,Behavioural risks,Child and maternal malnutrition,Vitamin A deficiency,62590.000000,17374.400000,233000.000000,8.000000,78090.700000,72735.600000,...,2689198.800000,26336244.300000,4.500000,3.100000,1.000000,10.900000,5.000000,0.700000,62590.0 (17374.4-233000.0),5795025.0 (2663755.7-29000000.0)
8,8,Behavioural risks,Child and maternal malnutrition,Zinc deficiency,27045.000000,1611.600000,97330.000000,8.000000,35349.100000,34587.600000,...,2209195.100000,8987553.000000,3.700000,2.800000,1.000000,61.500000,16.300000,1.400000,27045.0 (1611.6-97330.0),2412825.0 (148447.0-9136000.0)
9,9,Behavioural risks,Dietary risks,Diet high in \nsugar sweetened beverages,131500.000000,22560.000000,299521.000000,8.000000,137766.400000,96057.500000,...,1403671.100000,7773490.000000,1.500000,1.600000,0.600000,11.000000,6.800000,0.400000,131500.0 (22560.0-299521.0),5320000.0 (779510.0-8553000.0)
10,10,Behavioural risks,Dietary risks,Diet high in processed meat,305676.900000,130000.000000,840857.000000,8.000000,400262.400000,251633.300000,...,5668500.000000,17742960.000000,1.800000,1.600000,0.600000,6.600000,3.200000,0.800000,305676.9 (130000.0-840857.0),10122314.8 (3196040.0-20939000.0)
11,11,Behavioural risks,Dietary risks,Diet high in red meat,72500.000000,25000.000000,895674.900000,8.000000,229208.500000,302693.000000,...,1721335.000000,22613743.800000,7.500000,3.300000,1.200000,19.100000,8.000000,0.900000,72500.0 (25000.0-895674.9),3000000.0 (1247330.0-23861073.8)
13,13,Behavioural risks,Dietary risks,Diet high in trans fatty acids,397119.100000,93310.700000,644981.000000,8.000000,372178.700000,175205.300000,...,2716000.000000,11742241.600000,1.200000,1.300000,0.400000,5.700000,4.000000,0.400000,397119.1 (93310.7-644981.0),10078200.7 (2491995.3-14234237.0)
17,17,Behavioural risks,Dietary risks,Diet low in fruits,2390600.000000,1046014.900000,4902242.000000,8.000000,2564252.100000,1201135.700000,...,13443276.700000,76416663.800000,1.200000,1.200000,0.400000,3.800000,2.300000,0.300000,2390600.0 (1046014.9-4902242.0),62891195.0 (27678336.2-104095000.0)
18,18,Behavioural risks,Dietary risks,Diet low in legumes,593529.800000,389328.800000,1116424.000000,5.000000,661350.500000,274670.500000,...,3214450.000000,15146471.800000,1.100000,1.000000,0.400000,2.700000,1.700000,0.300000,593529.8 (389328.8-1116424.0),14214450.0 (9162566.8-24309038.5)
20,20,Behavioural risks,Dietary risks,Diet low in nuts and seeds,1627500.000000,575139.200000,2471823.000000,8.000000,1516373.300000,767055.800000,...,12334500.000000,37693903.500000,1.000000,1.100000,0.500000,3.800000,2.800000,0.500000,1627500.0 (575139.2-2471823.0),38260000.0 (13595096.5-51289000.0)
21,21,Behavioural risks,Dietary risks,Diet low in seafood omega-3 fatty acids,1210448.000000,337279.700000,1538760.000000,8.000000,1044722.100000,485601.400000,...,7550420.000000,25938185.100000,1.000000,1.100000,0.400000,4.500000,3.400000,0.400000,1210448.0 (337279.7-1538760.0),25323500.0 (7409654.9-33347840.0)
22,22,Behavioural risks,Dietary risks,Diet low in vegetables,1489825.000000,529381.300000,1994000.000000,8.000000,1359666.200000,524678.900000,...,7059455.000000,31678761.500000,0.900000,1.000000,0.300000,3.400000,2.700000,0.300000,1489825.0 (529381.3-1994000.0),34844545.0 (12953238.5-44632000.0)
27,27,Behavioural risks,Intimate partner violence,Intimate partner violence,115671.400000,61276.900000,197000.000000,8.000000,124759.300000,59894.700000,...,4312780.300000,12966809.400000,1.200000,1.100000,0.400000,3.300000,2.000000,0.600000,115671.4 (61276.9-197000.0),11150482.1 (5575290.0-18542099.4)
28,28,Behavioural risks,Low physical activity,Low physical activity,1316670.000000,657618.700000,3183940.000000,8.000000,1470435.900000,863853.900000,...,8281480.700000,53613039.600000,2.200000,1.800000,0.600000,4.400000,2.900000,0.500000,1316670.0 (657618.7-3183940.0),24007930.0 (15704960.4-69318000.0)
30,30,Behavioural risks,Tobacco,Chewing tobacco,66421.600000,55592.200000,251383.300000,4.000000,109954.700000,94747.200000,...,192798.600000,4979150.900000,2.900000,1.700000,0.800000,4.300000,3.700000,0.200000,66421.6 (55592.2-251383.3),1735925.5 (1504402.8-6483553.8)
31,31,Behavioural risks,Tobacco,Second-hand smoke,1053000.000000,331000.000000,1661777.800000,8.000000,1022632.700000,429728.300000,...,6620308.800000,35562750.300000,1.200000,1.200000,0.400000,4.800000,3.200000,0.300000,1053000.0 (331000.0-1661777.8),30054553.8 (9316000.0-44878750.3)
44,44,Environmental/occupational risks,Occupational risks,Occupational carcinogens,345111.400000,118097.000000,746540.000000,8.000000,379023.200000,179700.000000,...,1253125.200000,18001730.000000,2.400000,2.100000,0.600000,7.700000,2.800000,0.200000,345111.4 (118097.0-746540.0),7529625.2 (2681000.0-20682730.0)
45,45,Environmental/occupational risks,Occupational risks,Occupational injuries,323600.300000,159000.000000,550628.200000,8.000000,353358.400000,139434.600000,...,4976000.000000,31944476.600000,1.400000,1.400000,0.400000,4.200000,2.200000,0.300000,323600.3 (159000.0-550628.2),22097267.8 (9947000.0-41891476.6)
50,50,Environmental/occupational risks,Other environmental risks,Lead exposure,877357.900000,495000.000000,3477003.700000,8.000000,1191588.300000,981410.900000,...,5354917.700000,64049765.800000,3.300000,2.500000,0.800000,7.900000,3.800000,0.400000,877357.9 (495000.0-3477003.7),19259692.7 (9287000.0-73336765.8)
51,51,Environmental/occupational risks,Other environmental risks,Other environmental risks,965209.500000,558000.000000,3560080.400000,8.000000,1272917.300000,984097.400000,...,5635540.000000,64568343.500000,3.000000,2.300000,0.700000,7.000000,3.600000,0.400000,965209.5 (558000.0-3560080.4),21191930.8 (10673000.0-75241343.5)
55,55,Environmental/occupational risks,"Unsafe water, sanitation, and handwashing",Unsafe water source,1195080.000000,116126.000000,1251000.000000,8.000000,973893.300000,401737.100000,...,15013145.900000,67350000.000000,1.200000,1.300000,0.400000,9.700000,7.500000,0.400000,1195080.0 (116126.0-1251000.0),58170325.0 (7775000.0-75125000.0)

## R/M analysis

### Across iteration year comparisons

In [78]:
summary_wide.rmu_Deaths.median()

0.8

In [79]:
print('Median range/median deaths risks 2010-2023: '+str(summary_wide.rmu_Deaths.median())+' ('+str(summary_wide.rmu_Deaths.min())+'-'+str(summary_wide.rmu_Deaths.max())+')',
    '\nMedian range/median daly risks 2010-2023: '+str(summary_wide.rmu_DALYs.median())+' ('+str(summary_wide.rmu_DALYs.min())+'-'+str(summary_wide.rmu_DALYs.max())+')')

Median range/median deaths risks 2010-2023: 0.8 (0.0-3.8)
Median range/median daly risks 2010-2023: 0.7 (0.1-3.3)

In [80]:
summary_wide.head(3)

,Unnamed: 0,Overarching_group,Group,Risk_factor,median_Deaths,min_Deaths,max_Deaths,n_estimates_Deaths,mean_Deaths,std_Deaths,...,mad_DALYs,range_DALYs,fold_range_vs_median_DALYs,rmu_DALYs,cv_DALYs,max_vs_min_DALYs,f_med_DALYs,rcv_m_DALYs,Median Deaths (Min-Max),Median DALYs (Min-Max)
0,0,All risk factors,Other,All risk factors,34086634.000000,30839000.000000,35000050.000000,7.000000,33397760.600000,1512548.300000,...,77525424.100000,275131730.100000,0.200000,0.200000,0.100000,1.300000,1.200000,0.100000,34086634.0 (30839000.0-35000050.0),1194160306.0 (996554000.0-1271685730.1)
1,1,Behavioural risks,Child and maternal malnutrition,Child and maternal malnutrition,2572941.400000,1414000.000000,3190000.000000,7.000000,2440717.300000,656497.000000,...,19710329.400000,154880000.000000,0.600000,0.600000,0.200000,1.900000,1.600000,0.100000,2572941.4 (1414000.0-3190000.0),275068980.0 (172120000.0-327000000.0)
2,2,Behavioural risks,Child and maternal malnutrition,Child growth failure,1037101.200000,888199.300000,1190000.000000,5.000000,1038117.300000,108409.000000,...,5237153.700000,25938542.900000,0.300000,0.300000,0.100000,1.400000,1.200000,0.100000,1037101.2 (888199.3-1190000.0),89759926.0 (74061457.1-100000000.0)

In [81]:
# Calculate medians for each group, skipping NaN values
behavioural_risks_median = summary_wide[summary_wide['Overarching_group'] == 'Behavioural risks'].rmu_Deaths.median(skipna=True)
environmental_risks_median = summary_wide[summary_wide['Overarching_group'] == 'Environmental/occupational risks'].rmu_Deaths.median(skipna=True)
metabolic_risks_median = summary_wide[summary_wide['Overarching_group'] == 'Metabolic risks'].rmu_Deaths.median(skipna=True)

# Print the results
print(f"Behavioural risks median R/M: {behavioural_risks_median}")
print(f"Environmental/occupational risks median R/M: {environmental_risks_median}")
print(f"Metabolic risks median R/M: {metabolic_risks_median}")

# Calculate medians for each group, skipping NaN values
behavioural_risks_median = summary_wide[summary_wide['Overarching_group'] == 'Behavioural risks'].rmu_DALYs.median(skipna=True)
environmental_risks_median = summary_wide[summary_wide['Overarching_group'] == 'Environmental/occupational risks'].fold_range_vs_median_DALYs.median(skipna=True)
metabolic_risks_median = summary_wide[summary_wide['Overarching_group'] == 'Metabolic risks'].rmu_DALYs.median(skipna=True)

# Print the results
print(f"Behavioural risks median R/M: {behavioural_risks_median}")
print(f"Environmental/occupational risks median R/M: {environmental_risks_median}")
print(f"Metabolic risks median R/M: {metabolic_risks_median}")

Behavioural risks median R/M: 1.05
Environmental/occupational risks median R/M: 0.7
Metabolic risks median R/M: 0.5
Behavioural risks median R/M: 0.8500000000000001
Environmental/occupational risks median R/M: 0.6
Metabolic risks median R/M: 0.6

In [82]:
# Sort by 'Overarching_group' first
sorted_summary = summary_wide.sort_values(by='Overarching_group')

# Group by 'Group' and calculate the median for the specified columns
group_medians = sorted_summary.groupby('Group')[['rmu_Deaths', 'rmu_DALYs']].median()

# Display the result
group_medians

                                           rmu_Deaths  rmu_DALYs
Group
Air pollution                                0.500000   0.500000
Child and maternal malnutrition              1.200000   0.550000
Dietary risks                                1.100000   1.000000
Drug use                                     1.000000   0.600000
High LDL cholesterol*                        0.600000   0.700000
High alcohol use                             0.600000   0.800000
High body-mass index                         0.400000   0.500000
High fasting plasma glucose                  0.600000   0.600000
High systolic blood pressure                 0.200000   0.300000
Intimate partner violence                    1.100000   1.100000
Kidney dysfunction*                          0.500000   0.600000
Low bone mineral density                     0.800000   1.400000
Low physical activity                        1.700000   1.800000
Non-optimal temperature                      0.200000   0.100000
Occupational risks                           1.000000   0.800000
Other                                        0.200000   0.250000
Other environmental risks                    2.400000   2.300000
Tobacco                                      0.850000   0.850000
Unsafe sex                                   0.500000   0.600000
Unsafe water, sanitation, and handwashing    0.900000   0.800000

### Matched comparisons

In [83]:
summary_wide_cons[summary_wide_cons['rmu_Deaths']>1.5].Risk_factor.unique()

array(['Iron deficiency', 'Vitamin A deficiency', 'Zinc deficiency',
       'Diet high in \nsugar sweetened beverages',
       'Diet high in red meat', 'Diet low in fruits',
       'Diet low in nuts and seeds',
       'Diet low in seafood omega-3 fatty acids',
       'Diet low in vegetables', 'Low physical activity',
       'Chewing tobacco', 'Lead exposure', 'Other environmental risks'],
      dtype=object)

In [84]:
# Calculate and print the proportion and count of rows where rmu_Deaths > 1
prop_deaths_gt1 = summary_wide_cons['rmu_Deaths'].gt(1).mean()
count_deaths_gt1 = summary_wide_cons['rmu_Deaths'].gt(1).sum()
print(f'prop >1 fold range Deaths, n: {prop_deaths_gt1}, {count_deaths_gt1}')

# Calculate and print the proportion and count of rows where rmu_DALYs > 1
prop_dalys_gt1 = summary_wide_cons['rmu_DALYs'].gt(1).mean()
count_dalys_gt1 = summary_wide_cons['rmu_DALYs'].gt(1).sum()
print(f'prop >1 fold range DALYs, n: {prop_dalys_gt1}, {count_dalys_gt1}')

prop >1 fold range Deaths, n: 0.21481481481481482, 145
prop >1 fold range DALYs, n: 0.17777777777777778, 120

In [38]:
print('Median range/median deaths risks 2010-2021: '+str(summary_wide_cons.rmu_Deaths.median())+' ('+str(summary_wide_cons.rmu_Deaths.min())+'-'+str(summary_wide_cons.rmu_Deaths.max())+')',
    '\nMedian range/median daly risks 2010-2021: '+str(summary_wide_cons.rmu_DALYs.median())+' ('+str(summary_wide_cons.rmu_DALYs.min())+'-'+str(summary_wide_cons.rmu_DALYs.max())+')')

Median range/median deaths risks 2010-2021: 0.36454829328193983 (0.0-2.5810824229773317)
Median range/median daly risks 2010-2021: 0.3291107969842606 (0.0-2.5256558237360025)

In [39]:
## IQR for deaths and DALYs
summary_wide_cons['rmu_Deaths'].quantile(0.25), summary_wide_cons['rmu_Deaths'].quantile(0.75)

(0.17751081424297907, 0.7711610755766243)

In [ ]:
summary_wide_cons['rmu_DALYs'].quantile(0.25), summary_wide_cons['rmu_DALYs'].quantile(0.75)

(0.14549279317698363, 0.7251634275470046)

In [ ]:
temps_comp[(temps_comp['Risk_factor'] == 'Metabolic risks') & (temps_comp['year_gbd'].isin([2013, 2023]))&(temps_comp['measure']=='Deaths')]